OPERATIONS := ((OPERATION | COMMENT) <nl>?)*

OPERATION := FROM <ws>+ <"->"> <ws>+ TO <ws>+ <":"> <ws>+ ACTION
COMMENT   := <"#">+ <ws>+ line

FROM   := string
TO     := string
ACTION := line

string := #'[^\s]+'
line   := #'.+'
nl     := #'\r?\n' (* new line *)
ws     := #'\s+'   (* whitespace *)